services:
  mysql:
    image: mysql:8.0
    container_name: mysql_envios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: grupo7POO
      MYSQL_DATABASE: envioslogistica
      MYSQL_USER: envioslogistica_user
      MYSQL_PASSWORD: grupo7poo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./envioslogistica.sql:/docker-entrypoint-initdb.d/envioslogistica.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  envioslogistica:
    build: .
    container_name: envios_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    # Cargar variables desde devcontainer.env
    env_file:
      - .env
    ports:
      - "8070:8070"
    # Montar el keystore SSL (solo en el server)
    #volumes:
    #  - /etc/letsencrypt/live/poo2025.unsada.edu.ar:/etc/letsencrypt/live/poo2025.unsada.edu.ar:ro

volumes:
  mysql_data:
